export default {
  User: "/user",
  Cinema: "/cinema",
  Comment: "/comment",
  Film: "/film",
  Room: "/room",
  Seat: "/seat",
  Session: "/session",
  Order: "/order",
  Type: "/type",
  Admin: "/admin",
  queryUser: (id) => "/user/" + id,
  queryAdmin: (id) => "/admin/" + id,
  queryCinema: (id) => "/cinema/" + id,
  queryComment: (id) => "/comment/" + id,
  queryFilm: (id) => "/film/" + id,
  queryRoom: (id) => "/room/" + id,
  querySeat: (id) => "/seat/" + id,
  querySession: (id) => "/session/" + id,
  queryOrder: (id) => "/order/" + id,
  queryType: (id) => "/type/" + id,

};
